#!/usr/bin/env python
import hashlib
import os
import subprocess
import sys

ANDROID_NDK_PKG = 'https://dl.google.com/android/repository/android-ndk-r13-linux-x86_64.zip'
ANDROID_NDK_SHA1 = 'a22bfcbe467103e21acc953b0c11158941ab49ee'

ANDROID_SDK_PKG = 'https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz'
ANDROID_SDK_SHA1 = '725bb360f0f7d04eaccff5a2d57abdd49061326d'

MODEL_PKG = 'https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip'
MODEL_SHA1 = 'e3b84c7e240ce8025b30d868f5e840b4bba9761d'

SHA1 = lambda x: hashlib.sha1(x).hexdigest()

FILES = [
    (ANDROID_SDK_PKG, ANDROID_SDK_SHA1, SHA1),
    (ANDROID_NDK_PKG, ANDROID_NDK_SHA1, SHA1),
    (MODEL_PKG, MODEL_SHA1, SHA1),
]

TARGET_DIR = 'ansible/downloads'

def check(url, checksum, check_fn):
    fn = os.path.join(TARGET_DIR, os.path.basename(url))
    if not os.path.exists(fn):
        return False

    with file(fn) as f:
        data = f.read()
        return check_fn(data) == checksum

def run_cmd(cmd):
    return subprocess.call(cmd, shell=True) == 0

def download(url, checksum, check_fn):
    if check(url, checksum, check_fn):
        print 'Already downloaded %s' % url
        return True

    dl_cmd = 'wget --tries=3 --continue --timestamping --directory-prefix=%s %s' % (TARGET_DIR, url)
    if not run_cmd(dl_cmd):
        return False

    return check(url, checksum, check_fn)

def main():
    for f in FILES:
        if not download(*f):
            print 'Download error, please try again'
            sys.exit(-1)
    '''
    if not os.path.exists('tensorflow'):
        clone_cmd = 'git clone https://github.com/tensorflow/tensorflow.git'
        if not run_cmd(clone_cmd):
            print 'Error cloning tensorflow'
            sys.exit(-1)
    '''

if __name__ == '__main__':
    main()
